sudo: true

language: node_js

node_js:
  - "6"

os:
  - osx
  - linux

before_install:
  - npm i -g yarn@latest 
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - yarn install
  - yarn vscode:prepublish

script:
  - yarn test